authProviders:
  - name: tokenx
    discoveryUrl: http://localhost:8081/default/.well-known/openid-configuration
    tokenEndpointUrl: http://localhost:8081/default/token
    clientId: paw-arbeidssokerregisteret-api
    claims:
      map:
        - acr=Level4
        - acr=idporten-loa-high
      combineWithOr: true
  - name: azure
    discoveryUrl: http://localhost:8081/default/.well-known/openid-configuration
    tokenEndpointUrl: http://localhost:8081/default/token
    clientId: paw-arbeidssokerregisteret-api
    claims:
      map:
        - NAVident
      combineWithOr: false
poaoClientConfig:
  url: http://localhost:8090/poao-tilgang/
  scope: api://test.test.poao-tilgang/.default
database:
  host: localhost
  port: 5432
  username: admin
  password: admin
  name: arbeidssokerregisteretapi
kafka:
  gruppeId: paw.arbeidssokerregisteret-soek-api-v1
  periodeTopic: paw.arbeidssokerperioder-beta-v1
  arbeidssokerOpplysningerTopic: paw.arbeidssoker-situasjon-beta-v1
  serverConfig:
    autentisering: PLAIN
    kafkaBrokers: localhost:9092
  schemaRegistryConfig:
    url: localhost:8082