authProviders:
  - name: tokenx
    discoveryUrl: ${TOKEN_X_WELL_KNOWN_URL}
    tokenEndpointUrl: ${TOKEN_X_TOKEN_ENDPOINT}
    clientId: ${TOKEN_X_CLIENT_ID}
    claims:
      map:
        - acr=Level4
        - acr=idporten-loa-high
      combineWithOr: true
  - name: azure
    discoveryUrl: ${AZURE_APP_WELL_KNOWN_URL}
    tokenEndpointUrl: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
    clientId: ${AZURE_APP_CLIENT_ID}
    claims:
      map:
        - NAVident
database:
  host: ${NAIS_DATABASE_PAW_KAFKA_KEY_GENERATOR_PAWKAFKAKEYS_HOST}
  port: ${NAIS_DATABASE_PAW_KAFKA_KEY_GENERATOR_PAWKAFKAKEYS_PORT}
  username: ${NAIS_DATABASE_PAW_KAFKA_KEY_GENERATOR_PAWKAFKAKEYS_USERNAME}
  password: ${NAIS_DATABASE_PAW_KAFKA_KEY_GENERATOR_PAWKAFKAKEYS_PASSWORD}
  name: ${NAIS_DATABASE_PAW_KAFKA_KEY_GENERATOR_PAWKAFKAKEYS_DATABASE}
kafka:
  brokerUrl: ${KAFKA_BROKERS}
  consumerGroupId: paw-arbeidssokerregisteret-api-v1
  consumers:
    arbeidssokerperioder:
      topic: ${KAFKA_CONSUMER_ARBEIDSSOKERPERIODER_TOPIC}