apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: paw-arbeidssokerregisteret-api-schema-registry
  namespace: paw
  labels:
    team: paw
spec:
  image: {{ image }}
  kafka:
    pool: nav-dev
  readiness:
    failureThreshold: 10
    initialDelay: 20
    path: /isReady
    periodSeconds: 5
    port: 8080
    timeout: 1
  liveness:
    failureThreshold: 10
    initialDelay: 20
    path: /isAlive
    periodSeconds: 5
    port: 8080
    timeout: 1
