apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: paw-arbeidssokerregisteret-api-schema-registry
  namespace: paw
  labels:
    team: paw
spec:
  liveness:
    failureThreshold: 10
    initialDelay: 20
    path: /isalive
    periodSeconds: 5
    port: 8080
    timeout: 1
  readiness:
    failureThreshold: 10
    initialDelay: 20
    path: /isready
    periodSeconds: 5
    port: 8080
    timeout: 1
  image: {{ image }}
  kafka:
    pool: nav-dev
