apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: paw-arbeidssokerregisteret-api-schema-registry
  namespace: paw
  labels:
    team: paw
spec:
  replicas:
    min: 1
    max: 1
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  image: {{ image }}
  kafka:
    pool: nav-dev
