apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: paw-arbeidssokerregisteret-api
  namespace: paw
  labels:
    team: paw
spec:
  image: {{ image }}
  ingresses:
    - https://arbeidssokerregisteret.intern.dev.nav.no
  port: 8080
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - NAVident
  tokenx:
    enabled: true
  kafka:
    pool: nav-dev
  env:
    - name: OTEL_METRICS_EXPORTER
      value: "none"
    - name: OTEL_TRACES_EXPORTER
      value: "maskert_oltp"
    - name: OTEL_JAVAAGENT_DEBUG
      value: "false"
  replicas:
    min: 1
    max: 1
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    tracing:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: tokenx-token-generator
          namespace: aura
          cluster: dev-gcp