gruppeId = "paw.arbeidssokerregisteret-soek-api-v1"
periodeTopic = "paw.arbeidssokerperioder-beta-v1"
arbeidssokerOpplysningerTopic = "paw.arbeidssoker-situasjon-beta-v1"

[serverKonfigurasjon]
autentisering = "PLAIN"
kafkaBrokers = "localhost:9092"
kafkaSchemaRegistry = "localhost:8082"

[schemaRegistryKonfigurasjon]
url = "localhost:8082"
